### ISSUE TITLE
External Link

### ISSUE THREAD

**Issue by rohapa** [kraftbj/press-this-extended#22]
This is great! But how do I get it to automatically fill in the external link?

**Comment by kraftbj** [comment]
When using the bookmarklet, it will do so automatically as part of core's feature set.

**Comment by rohapa** [comment]
It's not working for me.

**Comment by rohapa** [comment]
Always comes up blank.
![77ad62fb-a4ef-46a2-b0ef-7c60db58f3eb](https://cloud.githubusercontent.com/assets/11214062/9009843/4b80c6ea-3769-11e5-8a33-e9f49317df16.png)

**Comment by kraftbj** [comment]
That meta box isn't part of WordPress Core (and so not something taken into consideration when making Press This). At this time, Core itself doesn't appear to have any hooks to set custom meta data. 

Opened up a ticket on Trac since this is a Core issue: https://core.trac.wordpress.org/ticket/33219#ticket

**Comment by rohapa** [comment]
My bad.... Thanks for your hard work!
